[package]
name = "schroedinger_box"
version = "0.0.1"
authors = ["P1start"]
description = """
A Rust container type modeled after Erwin Schrödinger’s famous thought
experiment.
"""
license = "MIT"
repository = "https://github.com/P1start/schroedinger_box"

[dependencies]
rand = "*"
